#!/bin/bash
set -e
export LOCAL_D=$(dirname "$0")
#export PyExe="pypy3"
export PyExe="python3"
# run dry in mp mode with default cfg
pushd $LOCAL_D
echo "make env in $LOCAL_D"
$PyExe -m venv ./_venv
PYBIN=$LOCAL_D/_venv/bin
$PYBIN/pip3 install --upgrade pip
$PYBIN/pip3 install -r $LOCAL_D/requirements_dry.txt
echo "make env - DONE"
popd

time $PYBIN/$PyExe $LOCAL_D/dry --noprescan --mp --progress $1