#!/bin/bash

shopt -s dotglob

process_file() {
    local file="$1"
    if file --mime-type "$file" | grep -q "text/"; then
        echo "--- $file ---"
        cat "$file"
    fi
}

export -f process_file

find . -type f -exec bash -c 'process_file "$0"' {} \;